[JEP-227] Prevent Stackoverflow during logout
jenkinsci/github-oauth-plugin pull request #122
Opened 2020-09-28 13:22 UTC by Wadeck

Due to the upcoming changes: https://github.com/jenkinsci/jenkins/pull/4848/files?file-filters%5B%5D=.java&hide-deleted-files=true#diff-7f1293bc6e17d8f944c084eaee7dad62R265-R279 there is an infinite loop when logging out.

Context information: https://github.com/jenkinsci/jep/tree/master/jep/227

@jglick

2020-09-28 16:16 UTC, jglick approved these changes
Hmm, yes, unfortunately `Util.isOverridden` tricks cannot easily handle the case where a method delegates to `super`. I suppose this is solvable using a `ThreadLocal<Boolean>` to check whether `getPostLogOutUrl2` is being called reëntrantly. Is there a simple way to reproduce the error you saw?

2020-09-28 16:32 UTC, jglick commented
Never mind, I think I reproduced this in a functional test and will look for a fix.

2020-09-28 17:02 UTC, jglick requested changes
https://github.com/jenkinsci/jenkins/pull/4848/commits/b6d5a6ee78c6bff991c6a527ca97d39f1b68d9ba should make this unnecessary.

2020-09-29 06:57 UTC, Wadeck commented
Thanks @jglick for the quick reaction!

2020-09-29 06:57 UTC, closed without merging